### ISSUE TITLE
Media used in profile

### ISSUE THREAD

**Issue by asadalibest1** [xtenzQ/xtenzQ#2]
Hi @xtenzQ, how are you, I hope you will fine in the current pandemic, I like your previous GitHub profile very much can you please share the material with me that you have use in your previous profile, [link](https://repository-images.githubusercontent.com/284729822/e8d9fc80-da8f-11ea-944c-5ce747e26c95)

**Comment by xtenzQ** [comment]
Hey, @asadalibest1! I recommend you to check this **[commit](https://github.com/xtenzQ/xtenzQ/tree/74f13169d0bf1d63500985ea06eb5a7f1a803b22)**. Feel free to use `readme.png` too. If you need SVG original, I can search it on my PC for you.

**Comment by xtenzQ** [comment]
@asadalibest1, this is a `.psd` for you [Developer_README.psd](https://drive.google.com/file/d/1fPoV4AHkHQ5YO1icC8BDib8f_pBoxrMO/view?usp=sharing) (hosted on Google Drive)

Language icons are created with [shields.io](https://shields.io/).

**Comment by asadalibest1** [comment]
Hi, **xtenzQ**, I am very very thankful to you for this kind act.

**Comment by xtenzQ** [comment]
@asadalibest1 you're welcome! Enjoy! :)
